# Generated by Django 5.2.8 on 2025-11-22 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mensagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enviado', models.CharField(choices=[('A', 'Usuário A'), ('B', 'Usuário B')], max_length=1)),
                ('texto', models.TextField()),
                ('texto_resposta', models.TextField(blank=True)),
                ('criado', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
