# Generated by Django 5.2.8 on 2025-11-24 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensagem',
            name='texto_resposta',
            field=models.TextField(blank=True, null=True),
        ),
    ]
